### ISSUE TITLE
Advice for including POSIX gateway setup and Guest Collections

### ISSUE THREAD

**Issue by JoshuaSBrown** [globus/globus-connect-server-deploy#3]
@JasonAlt do you have any suggestions for how to go about including the steps for auto-configuring a POSIX storage gateway as well as how to include a guest collection? 

I am having a hard time figuring out which pieces:

1. I can automatically configure and package as part of a container 
2. what has to be done manually on starting the container due to the web UI link included as part of the authentication flow
3. what has to be done before hand on the host operating system before running the container.

For instance, if I have a GCS container running in cluster and it dies, what state needs to be preserved so that I can auto-restart it. Containers are by nature ephemeral so I am unsure what would need to persist?

**Comment by JasonAlt** [comment]
(I'm glad you mentioned me directly, my notifications for this repo were not working)

> steps for auto-configuring a POSIX storage gateway as well as how to include a guest collection

If you assign the administrator role to an auth client, you'll be able to make use of the CLI or the GCS API to do both of these things.

> I can automatically configure and package as part of a container

Nothing about the endpoint's configuration resides in the image. When the container is instantiated, the endpoint's encrypted configuration is downloaded into the container's local DB which is then used by GCS. While the container must be available to configure the endpoint (more precisely, one GCS node in the endpoint needs to be active), the configuration is not persisted there. If you were, for example, to make an image from a running GCS container, the next time that image is turned into a container, GCS will overwrite (actually merge updates into) the local node's database.

> what has to be done manually on starting the container due to the web UI link included as part of the authentication flow

This is the current hiccup in full automation. I know that recent changes to `endpoint setup` prevent fully non-interactive endpoint configuration, start to finish. I have it on my queue to fix. If you encounter others, let me know.

> what has to be done before hand on the host operating system before running the container

The GCS images are just a fresh install of the OS distro + GCS. Then a script is added (since docker + systemd do not play nice) to essentially do `node setup` on start and `node cleanup` on teardown. The only things you should have to do is to mount local posix file systems into the container (for data transfers) and make sure passwd/group translations are working within the container. Other than that, you'll want to make sure you have a plan for capturing logging from the containers.

>  if I have a GCS container running in cluster and it dies, what state needs to be preserved so that I can auto-restart it.

Nothing. You should already have the client ID, secret and deployment key which is enough to recreate the container with the configured endpoint. The gotcha here is in when containers die, the container doesn't always have a chance to run `node cleanup` before exiting. So you'd want some logic to make sure that recreating a node (instantiating a container) while a previous instance of then node is configured as `active` within the endpoint.

**Comment by JasonAlt** [comment]
Closing as inactive.
